server:
  port: 9001

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prashanth844/-project-file.git
          clone-on-start: true

profiles:
  active: dev

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka
